# following https://github.com/coq-community/docker-coq-action

name: Docker CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - dev
          - '8.20'
          - '8.19'
        coq-hol-light-version:
          - dev
          - '3.0.0'
          - '2.0.0'
          - '1.0.0'
          - '0.0.0'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-hol-light-real-with-N.opam'
          coq_version: ${{ matrix.coq_version }}
      - name: check coq-hol-light
        run: opam install coq-hol-light.${{ matrix.coq-hol-light-version }}
