# following https://github.com/coq-community/docker-coq-action

name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:

  coq--coq-hol-light:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        coq_version: [dev, '8.20', 8.19]
        coq-hol-light_version: [3.0.0] #2.0.0, 1.0.0, 0.0.0
    steps:
      - uses: actions/checkout@v4
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-hol-light-real-with-N.opam'
          coq_version: ${{ matrix.coq_version }}
          after_script: opam install -y coq-hol-light.${{ matrix.coq-hol-light_version }}

  coq--coq-hol-light-dev:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        coq_version: ['8.20', 8.19]
    container:
      image: coqorg/coq.${{ coq_version }}
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - run: |
          opam install -y .
          mkdir tmp
          cd tmp
          git checkout git@github.com:Deducteam/coq-hol-light.git
          cd coq-hol-light
          opam install -y .

  rocq--coq-hol-light-dev:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        coq_version: ['9.0']
    container:
      image: rocq/rocq-prover.${{ coq_version }}
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - run: |
          opam install -y .
          mkdir tmp
          cd tmp
          git checkout git@github.com:Deducteam/coq-hol-light.git
          cd coq-hol-light
          opam install -y .
